# Menu config
# 菜单配置

[[main]]
  identifier = "posts"
  # you can add extra information before the name (HTML format is supported), such as icons
  # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
  pre = ""
  # you can add extra information after the name (HTML format is supported), such as icons
  # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
  post = ""
  name = "文章"
  url = "/posts/"
  # title will be shown when you hover on this menu link.
  # 将鼠标悬停在此菜单链接上时将显示标题。
  title = ""
  weight = 1
[[main]]
  identifier = "tags"
  pre = ""
  post = ""
  name = "标签"
  url = "/tags/"
  title = ""
  weight = 2
[[main]]
  identifier = "series"
  pre = ""
  post = ""
  name = "系列"
  url = "/series/"
  title = ""
  weight = 3
[[main]]
  identifier = "navigation"
  pre = "<i class='fas fa-compass'></i>"
  post = ""
  name = "导航"
  url = "https://nav.bahuangshanren.tech"
  title = "自用的导航网站"
  weight = 4
[[main]]
  identifier = "travelling"
  pre = "<i class='fas fa-subway'></i>"
  post = ""
  name = "开往"
  url = "https://www.travellings.cn/go.html"
  title = "开往友链接力"
  weight = 5
[[main]]
  identifier = "wormhole"
  pre = "<i class='fas fa-circle-notch fa-spin'></i>"
  post = ""
  name = "虫洞"
  url = "https://www.foreverblog.cn/go.html"
  title = "十年之约友链接力"
  weight = 6
